Ultimaker/um-kernel

- dts/sun7i-a20-opinicus_emmc_v1.dts
UART3 used for marlin communication is a 4 pin port, it has rx, tx and RTS CTS
lines. We are not using the RTS and CTS line, but noise may trigger false
interrupts here. Ignore the CTS bits from the uart.
EM-1534
Signed-off-by: Olliver Schinagl <o.schinagl@ultimaker.com>
> EM-1543 - Ignore CTS pin to reduce IRQ storm

- dts/jedi-common.dts
Port G is powered by LDO4, but LDO4 is set to 2.8 volt by default.
Ensure there is at least enough power on LDO4 available.
Note that currently this is only a cosmetic/futureproofing fix.
U-Boot is currently responsible for setting the initial voltage of
LDO4. To fix this, a consumer is needed on the IO controller.
EM-1631
Signed-off-by: Olliver Schinagl <o.schinagl@ultimaker.com>
> Ensure there is 3.3 volt on port G

- dts/part2005-olimexinterface.dtsi
- dts/part2621-ultimainboard3.1.dtsi
This patch enables rfkill to be used on our usb hosts. Currently,
rfkill is not the designed framework for this, as it is explicitly
described for radio-frequency devices, but until we have a devkill or
similar device for this purpose, it will have to 'abuse' rfkill. This
abuse happens only in the devicetree. The kernel itself just see's a
wifi gpio.
Contributes to issue: EM-2406
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
> EM-2406 Add support for rfkill on our usb hosts

- initramfs/init.sh
The startup script needs to know on which device to perform operations.
As such, we need to pass the current root device along.
Addresses EMP-272, contributes to EMP-391.
Signed-off-by: Olliver Schinagl <oliver@schinagl.nl>
> Add root device to startup script parameters

- initramfs/init.sh
And pass device instead of passing root as an argument,
this makes the intention more clear.
Contributes to EMP-272, adresses to EMP-395
> Change the filename of the entrypoint script

- initramfs/init.sh
The interface changed for the jedi-system-update/start_udpate.sh script,
but the tracing output was still using the old variable that do not
exist anymore.
Contributes to EMP-421
> Fix error UPDATE_ROOT not found.

- initramfs/init.sh
When performing the update the disk_prepare script finds the disk in
use, this is caused because of a missing unmount in the init.sh script
before performing the pre-update.sh script
[EMP-523]
> EMP-523_Unmounting update source after package moved

- build_for_ultimaker.sh
The kernel build was failing because the busybox version URL is broken.
It has been updated to a new version. For now implemented a workaround
with a new version URL and at least notify the user if something is
wrong with the download.
An issue is logged to implement a proper fix EMP-20.
This issue addresses EMP-538.
version is now: busybox-static-1.28.4-r3
> Fix error in kernel build because of broken download URL.

- build_for_ultimaker.sh
Dependent modules had to be added manually to initrd module list before,
which was a time-consuming and error-prone process.
EMP-537
> Resolve module dependencies automatically for initrd

- build_for_ultimaker.sh
- initramfs/init.sh
In order to be able to show images on the framebuffer for the
ne update mechanism, the framebuffer must be available in the
initrd stage, i.e. the stage wherein the update tooling is executed.
Contributes to EMP-479 addresses EMP-554
> [EMP-554] Add S5 graphics module driver loading to initrd

- initramfs/init.sh
Bug in comparing string -eq is for numerical comparison.
> Fix unable to control recovery console from uboot

- .gitmodules
The submodule was setup to use https, not making use of
publick-key authentication.
> Fix 'login required for Linux submodule'

- dts/msc-sm2-imx6x.dtsi
MSC EDK carrier board contains an SGT15000 audio codec, but the UltiMainboard v4.x contains a MAX98357A amplifier (U11) audio amplifier, which is used as a codec. This configuration is changed in the device-tree.
solves: EMP-586
> Replaced audio codec

- build_for_ultimaker.sh
Fixed the dependency error for embedding the drivers in the initramfs and refactored to script in preparation for further CI work by boy scouting and fixing 'shellcheck linting errors'. 
shellcheck is a static code analysis 'linting' package for shell scripts.  
To run the latest version always, add the following line (alias) to your ~/.bashrc file: 
`alias shellcheck='docker run -v "$PWD:/mnt" koalaman/shellcheck'`
The pull the shellcheck docker image with: 
`docker pull koalaman/shellcheck`
Now you can check every shellscript on the commandline with: 
`shellcheck [script name]`
> Emp 607 fix dependency issues initramfs build

- .gitlab-ci.yml
- Dockerfile
- build_for_ultimaker.sh
- run_linter.sh
Addresses suggestions from @raysiudak.
- Docker now uses Debian jessie.
- Made Git variables global.
- Instruct Gitlab to shallowly clone. (EMP-646)
- Don't lint non-existent legacy-tests.
Pass on arguments to build.sh
- Docker needs to run with an interactive terminal (-it) for menuconfig to work.
> EMP-366 Additional improvements

- initramfs/init.sh
Normally in the um-kernel initrd process, the device where the um-update.swu image
is found is passed as the target update storage device. Altough this is correct for
a firmware update, it does not work for a firmware restore. When restoring we want to
update the eMMC instead of the MMC.
Unfortunately it is not trivial to determine what storage device is the SD card and
which is the internal flash. Therefore the 'recovery_data' partition is introduced
to serve as a recognition point to know if we are restoring or updating.
> Fix error with target update device when running from restore img

- .gitlab-ci.yml
- build.sh
- build_for_ultimaker.sh
- ci/cleanup_environment.sh
- ci/prepare_environment.sh
- ci/push_environment.sh
- run_linter.sh
Previously, a Docker image was rebuilt by rules specified in 'only'.
This caused a situation where a build with an updated Dockerfile would
succeed once, since Gitlab bases this rule on the previous commit.
A subsequent build would thus use the master branch Dockerfile,
since there were no changes according to Gitlab.
We decided that space on our runner (Dave) is more precious than CPU
power. So when a branch has a modified Dockerfile, Dave will rebuild
the Docker image for every build.
Since this behavior is not supported by Gitlab by default, we will
implement it using scripts. This causes build steps to show up in the
Gitlab interface, even though they don't do anything. This was
considered acceptable.
Signed-off-by: martijnbruinenberg <m.bruinenberg@ultimaker.com>
> EMP 645 Improve CI docker logic

- initramfs/init.sh
This is not a problem, it is just the modprobe tool telling us
that its missing dependencies. These are in turn resolved impplicitely
by depmod, making sure the dependent modules are loaded. This is
only visible because we use modprobe with the verbose flag.
This is fixed by making the module inclusion explicit and in the
right order.
Fixes EMP-877.
> [EMP-877] Fix symbols not found while loading framebuffer modules in initrd

- dts/imx8mm-cgtsx8m-ultimain5.0-lvds-1024x600.dts
- rt_boot_sel.sh
These pins are required to put the i.MX-RT in SDP (Serial Download Protocol) mode, we use this for field programming.
> Bring up i.MX-RT bootloader control pins

- dts/imx8mm-cgtsx8m-ultimain5.0-lvds-1024x600.dts
**Problem:** When booting the system, we see this error message:
at24 1-0057: Error applying setting, reverse things back
at24: probe of 1-0057 failed with error -22
**Cause:** In the 1-0057 eeprom (in ultiboard) device tree entry, we have some invalid configuration which blocks the driver from proper configuring the device.
Actually this configuration is only allowed in newer version of the eeprom driver (starting in kernel 4.19.xxx) and we using the kernel 4.14.98.
@dts/imx8mm-cgtsx8m-ultimain5.0-lvds-1024x600.dts
```
&i2c2 {
/* Carrier data EEPROM (U12) */
carrierdata@57 {
compatible = "atmel,24c32";
reg = <0x57>;
pinctrl-names = "default"         // Not allowed (invalid)
pinctrl-0 = <&pinctrl_gpio4>;     // Not allowed (invalid)
pagesize = <32>;
wp-gpios = <&gpio4 10 0>;         // …
```
> [CES-974] - Fix device tree entry for the ultiboard eeprom.
